module.exports = {
  plugins: ['@cypress/json'],
  settings: {
    'json/json-with-comments-files': [],
    'json/package-json-sort-order': [
      'name',
      'version',
      'private',
      'description',
      'license',
      'keywords',
      'author',
      'repository',
      'homepage',
      'bugs',
      'engines',
      'scripts',
      'bin',
      'type',
      'exports',
      'main',
      'browser',
      'module',
      'svelte',
      'types',
      'typesVersions',
      'files',
      'workspaces',
      'dependencies',
      'devDependencies',
      'peerDependencies',
      'resolutions',
      'browserslist',
      'eslintConfig',
      'prettier',
    ],
  },
}
